# Loading data

In [59]:
#prepare data
import pandas as pd
import numpy as np
from matplotlib.colors import ListedColormap
from sklearn.datasets import make_blobs
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn import datasets
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
#load data
from sklearn.svm import SVC
data_features = pd.read_csv('../data/features_voice.csv', thousands=' ')
# Dropping unneccesary columns
data_features = data_features.drop(['filename'],axis=1)

# Dividing data into training and Testing set

In [60]:
X=data_features.drop('label',axis=1)
print(X)
y=data_features['label']
print(y)

      chroma_stft  spectral_centroid  spectral_bandwidth      rolloff  \
0        0.561047        1216.076584         1906.471303  2887.243652   
1        0.395306        1983.098260         1822.039604  3750.260656   
2        0.552942        1674.140499         1978.852766  3797.674006   
3        0.563875        1242.391957         1854.850881  2550.761719   
4        0.240719        1965.831858         1970.560459  3531.859413   
...           ...                ...                 ...          ...   
1995     0.229706        2294.370268         2179.180387  4479.675293   
1996     0.508613        1393.119457         1820.942231  2847.883142   
1997     0.385498        2453.669717         2066.092839  4376.857592   
1998     0.261117        2145.111511         2083.967342  4066.805294   
1999     0.280005        2193.184858         2053.951109  4121.685791   

      zero_crossing_rate       mfcc1       mfcc2      mfcc3      mfcc4  \
0               0.033928 -304.606567  105.816933 

In [61]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2)

# Fitting

In [62]:
svm = SVC(kernel='linear')
svm.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [63]:
from sklearn.metrics import accuracy_score
y_pred=svm.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.9425


In [64]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[89  0  0  0  0]
 [ 0 66  2  0  0]
 [ 0  3 83  1  0]
 [ 1  7  2 68  3]
 [ 0  2  0  2 71]]
              precision    recall  f1-score   support

      avanza       0.99      1.00      0.99        89
     derecha       0.85      0.97      0.90        68
     detente       0.95      0.95      0.95        87
        gira       0.96      0.84      0.89        81
   izquierda       0.96      0.95      0.95        75

    accuracy                           0.94       400
   macro avg       0.94      0.94      0.94       400
weighted avg       0.95      0.94      0.94       400



In [65]:
from sklearn.externals import joblib
joblib.dump(svm, "../models/my_model_2.pkl") # save
my_model_loaded = joblib.load("../models/my_model_2.pkl") # load